# Generated by Django 5.0.4 on 2024-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsapp', '0002_alter_genre_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images/', verbose_name=''),
        ),
    ]
