version: '3'

services:
  django:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_DB=musiclab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=musiclab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  vue:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
