# Generated by Django 5.0.4 on 2024-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('myauth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='blogs.group'),
        ),
    ]
